RockyASPMVC/Models/ApplicationType.cs
using System.ComponentModel.DataAnnotations;

namespace RockyASPMVC.Models
{
    public class ApplicationType
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

RockyASPMVC/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RockyASPMVC.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        [Range(1,int.MaxValue, ErrorMessage = 
            "Display Order must be greater than zero")]
        [DisplayName("Display Order")]
        public int DisplayOrder { get; set; }
    }
}

RockyASPMVC/Models/ErrorViewModel.cs
using System;

namespace RockyASPMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RockyASPMVC/Models/Product.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RockyASPMVC.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        [Range(1, int.MaxValue)]
        public double Price { get; set; }
        public string Image { get; set; }

        [DisplayName("Category Type")]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")] 
        public virtual Category Category { get; set; }
    }
}

RockyASPMVC/Controllers/ApplicationTypeController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using RockyASPMVC.Data;
using RockyASPMVC.Models;

namespace RockyASPMVC.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationTypeController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> appTypes = _context.ApplicationType;
            return View(appTypes);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType appType)
        {
            if (!ModelState.IsValid) return View();
            
            _context.ApplicationType.Add(appType);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Edit(int? id)
        {
            if (id is null or < 1)
            {
                return NotFound();
            }

            var appType = _context.ApplicationType.Find(id);
            if (appType == null)
            {
                return NotFound();
            }
            return View(appType);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType appType)
        {
            if (!ModelState.IsValid) return View();
            
            _context.ApplicationType.Update(appType);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Delete(int? id)
        {
            if (id is null or < 1)
            {
                return NotFound();
            }

            var appType = _context.ApplicationType.Find(id);
            if (appType == null)
            {
                return NotFound();
            }
            return View(appType);
        }

        [HttpPost]
        public IActionResult Delete(ApplicationType appType)
        {
            _context.ApplicationType.Remove(appType);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RockyASPMVC/Controllers/CategoryController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using RockyASPMVC.Data;

namespace RockyASPMVC.Controllers
{
    public class Category : Controller
    {
        private readonly ApplicationDbContext _context;

        public Category(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // GET
        public IActionResult Index()
        {
            IEnumerable<Models.Category> categories = _context.Category;
            return View(categories);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Models.Category category)
        {
            if (!ModelState.IsValid) return View();
            
            _context.Category.Add(category);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id < 1)
            {
                return NotFound();
            }

            var category = _context.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Models.Category category)
        {
            if (!ModelState.IsValid) return View();
            
            _context.Category.Update(category);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1)
            {
                return NotFound();
            }

            var category = _context.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Delete(Models.Category category)
        {
            _context.Category.Remove(category);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RockyASPMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RockyASPMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RockyASPMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RockyASPMVC/Views/ApplicationType/Create.cshtml
@model ApplicationType

@{
    ViewBag.Title = "Create";
}
<form method="post">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-2">Add Application Type</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" value="Create" class="btn btn-info w-100"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{ <partial name="_ValidationScriptsPartial"/> }
}

RockyASPMVC/Views/ApplicationType/Delete.cshtml
@model ApplicationType

@{
    ViewBag.Title = "Delete";
}
<form method="post">
    <input type="hidden" asp-for="Id"/>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-2">Delete Application Type</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" disabled/>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" value="Delete" class="btn btn-danger w-100"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

RockyASPMVC/Views/ApplicationType/Edit.cshtml
@model ApplicationType

@{
    ViewBag.Title = "Edit";
}
<form method="post">
    <input type="hidden" asp-for="Id"/>
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-2">Edit Application Type</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" value="Update" class="btn btn-info w-100"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{ <partial name="_ValidationScriptsPartial"/> }
}

RockyASPMVC/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>

@{
    ViewBag.Title = "Index";
}

<div class="container p-3">
    <div class="row pt-3">
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> Add Application Type
            </a>
        </div>
    </div>
    <br/><br/>
    
    @if (Model.Any())
    {
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>
                    Category Name
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">@obj.Name</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-primary mx-3">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-3">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
            
            </tbody>
        </table>
    }
    else
    {
        <p>No Application Type exists</p>
    }
    
</div>

RockyASPMVC/Views/Category/Create.cshtml
@model Category

@{
    ViewBag.Title = "Create";
}
<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-2">Add Category</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control"/>
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" value="Create" class="btn btn-info w-100"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{ <partial name="_ValidationScriptsPartial"/> }
}

RockyASPMVC/Views/Category/Delete.cshtml
@model Category

@{
    ViewBag.Title = "Delete";
}
<form method="post">
    <input type="hidden" asp-for="Id"/>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-2">Delete Category</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" disabled/>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" disabled/>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" value="Delete" class="btn btn-danger w-100"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

RockyASPMVC/Views/Category/Edit.cshtml
@model Category

@{
    ViewBag.Title = "Edit";
}
<form method="post">
    <input type="hidden" asp-for="Id"/>
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-2">Edit Category</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control"/>
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" value="Update" class="btn btn-info w-100"/>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-primary w-100">
                                <i class="fas fa-sign-out-alt"></i> Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts
{
    @{ <partial name="_ValidationScriptsPartial"/> }
}

RockyASPMVC/Views/Category/Index.cshtml
@model IEnumerable<RockyASPMVC.Models.Category>

@{
    ViewBag.Title = "Index";
}

<div class="container p-3">
    <div class="row pt-3">
        <div class="col-6">
            <h2 class="text-primary">Category List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
               <i class="fas fa-plus"></i> Add Category
            </a>
        </div>
    </div>
    <br/><br/>
    
    @if (Model.Any())
    {
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>
                    Category Name
                </th>
                <th>
                    Display Order
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">@obj.Name</td>
                    <td width="30%">@obj.DisplayOrder</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a asp-action="Edit" asp-route-Id="@obj.Id" class="btn btn-primary mx-3">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-3">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
            
            </tbody>
        </table>
    }
    else
    {
        <p>No category exists</p>
    }
    
</div>

RockyASPMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RockyASPMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RockyASPMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RockyASPMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RockyASPMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>